/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrearRouteImport } from './routes/crear'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as IdiomaRouteImport } from './routes/idioma'
import { Route as MiPerfilRouteImport } from './routes/mi-perfil'
import { Route as PublicadoRouteImport } from './routes/publicado'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PanelIdRouteImport } from './routes/panel.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearRoute = CrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const IdiomaRoute = IdiomaRouteImport.update({
  id: '/idioma',
  path: '/idioma',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPerfilRoute = MiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicadoRoute = PublicadoRouteImport.update({
  id: '/publicado',
  path: '/publicado',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIdRoute = PanelIdRouteImport.update({
  id: '/panel/$id',
  path: '/panel/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/idioma': typeof IdiomaRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/publicado': typeof PublicadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/panel/$id': typeof PanelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/idioma': typeof IdiomaRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/publicado': typeof PublicadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/panel/$id': typeof PanelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crear': typeof CrearRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/idioma': typeof IdiomaRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/publicado': typeof PublicadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/panel/$id': typeof PanelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crear'
    | '/entrar'
    | '/explorar'
    | '/idioma'
    | '/mi-perfil'
    | '/publicado'
    | '/sitemap.xml'
    | '/panel/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crear'
    | '/entrar'
    | '/explorar'
    | '/idioma'
    | '/mi-perfil'
    | '/publicado'
    | '/sitemap.xml'
    | '/panel/$id'
  id:
    | '__root__'
    | '/'
    | '/crear'
    | '/entrar'
    | '/explorar'
    | '/idioma'
    | '/mi-perfil'
    | '/publicado'
    | '/sitemap.xml'
    | '/panel/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrearRoute: typeof CrearRoute
  EntrarRoute: typeof EntrarRoute
  ExplorarRoute: typeof ExplorarRoute
  IdiomaRoute: typeof IdiomaRoute
  MiPerfilRoute: typeof MiPerfilRoute
  PublicadoRoute: typeof PublicadoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PanelIdRoute: typeof PanelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear': {
      id: '/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof CrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idioma': {
      id: '/idioma'
      path: '/idioma'
      fullPath: '/idioma'
      preLoaderRoute: typeof IdiomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-perfil': {
      id: '/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof MiPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicado': {
      id: '/publicado'
      path: '/publicado'
      fullPath: '/publicado'
      preLoaderRoute: typeof PublicadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/$id': {
      id: '/panel/$id'
      path: '/panel/$id'
      fullPath: '/panel/$id'
      preLoaderRoute: typeof PanelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrearRoute: CrearRoute,
  EntrarRoute: EntrarRoute,
  ExplorarRoute: ExplorarRoute,
  IdiomaRoute: IdiomaRoute,
  MiPerfilRoute: MiPerfilRoute,
  PublicadoRoute: PublicadoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PanelIdRoute: PanelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
